
package com.Udec.enviosGUI;
import com.Udec.enviosBL.ConductorBL;
import com.Udec.enviosDAL.Conexion;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class frmConductor extends javax.swing.JFrame {
    
    /**
     * Creates new form frmEnvios
     */
    DefaultTableModel Modelo;
    public frmConductor() {
        
        initComponents();
        
        String[] titulos = {"idConductor","Nombre","Telefono"};
        
        Modelo = new DefaultTableModel(null, titulos);
        TablaConductor.setModel(Modelo);
        
        MostrarDatos();
        Limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConductor = new javax.swing.JTable();
        AgregarBoton = new javax.swing.JButton();
        EditarBoton = new javax.swing.JButton();
        BorrarBoton = new javax.swing.JButton();
        CancelarBoton = new javax.swing.JButton();
        TextIDConductor = new javax.swing.JTextField();
        TextNombreConductor = new javax.swing.JTextField();
        TextTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaConductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaConductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConductorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaConductor);

        AgregarBoton.setText("Agregar");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });

        EditarBoton.setText("Editar");
        EditarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBotonActionPerformed(evt);
            }
        });

        BorrarBoton.setText("Borrar");
        BorrarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarBotonActionPerformed(evt);
            }
        });

        CancelarBoton.setText("Cancelar");
        CancelarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBotonActionPerformed(evt);
            }
        });

        TextIDConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIDConductorActionPerformed(evt);
            }
        });

        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });

        jLabel1.setText("Telefono");

        jLabel2.setText("Nombre");

        jLabel3.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(TextIDConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TextTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                                        .addComponent(TextNombreConductor, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgregarBoton)
                                .addGap(65, 65, 65)
                                .addComponent(EditarBoton)
                                .addGap(91, 91, 91)
                                .addComponent(BorrarBoton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CancelarBoton)
                                .addGap(9, 9, 9)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(TextIDConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarBoton)
                    .addComponent(EditarBoton)
                    .addComponent(BorrarBoton)
                    .addComponent(CancelarBoton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextIDConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIDConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIDConductorActionPerformed

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void EditarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBotonActionPerformed
        // TODO add your handling code here:
        Conexion obj1 = new Conexion();
        ConductorBL obj2 = recuperarDatosGUI();
        String strSentenciaInsert = String.format("UPDATE conductor SET nombre='%s', "
                + "telefono='%s' WHERE idConductor='%s'", obj2.getNombre(), obj2.getTelefono(), obj2.getID());
        obj1.ejecutarSentenciasSQL(strSentenciaInsert);
        this.MostrarDatos();
        this.Limpiar();
    }//GEN-LAST:event_EditarBotonActionPerformed

    private void BorrarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarBotonActionPerformed
        // TODO add your handling code here:
        Conexion obj1 = new Conexion();
        ConductorBL obj2 = recuperarDatosGUI();
        String strSentenciaInsert = String.format("DELETE FROM conductor WHERE idConductor=%s",obj2.getID());
        obj1.ejecutarSentenciasSQL(strSentenciaInsert);
        this.MostrarDatos();
        this.Limpiar();
    }//GEN-LAST:event_BorrarBotonActionPerformed

    private void CancelarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBotonActionPerformed
        // TODO add your handling code here:
        
        this.Limpiar();
    }//GEN-LAST:event_CancelarBotonActionPerformed

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
        // TODO add your handling code here:
        Conexion obj1 = new Conexion();
        ConductorBL obj2 = recuperarDatosGUI();
        String strSentenciaInsert = String.format("INSERT INTO conductor(idConductor, nombre, telefono) "
                + "VALUES ('%s', '%s', '%s')", obj2.getID(), obj2.getNombre(), obj2.getTelefono());
        obj1.ejecutarSentenciasSQL(strSentenciaInsert);
        
        try {
            ResultSet resultado = obj1.consultarRegistros("SELECT * FROM envios.conductor");
            while (resultado.next()) {
                System.out.println(resultado.getString("idConductor"));
                System.out.println(resultado.getString("Nombre"));
                System.out.println(resultado.getString("Telefono"));
                System.out.println("");
            }
        } catch (Exception e) {
            System.out.println("error: "+e);
        }
        
        this.MostrarDatos();
        this.Limpiar();
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void TablaConductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConductorMouseClicked
        // TODO add your handling code here:
        
        if (evt.getClickCount()==1){
            JTable receptor = (JTable) evt.getSource();
            TextIDConductor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            TextNombreConductor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            TextTelefono.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
        }
        
        AgregarBoton.setEnabled(false);
        EditarBoton.setEnabled(true);
        BorrarBoton.setEnabled(true);
    }//GEN-LAST:event_TablaConductorMouseClicked
    public ConductorBL recuperarDatosGUI (){
        ConductorBL objConductor = new ConductorBL();
        objConductor.setID(TextIDConductor.getText());
        objConductor.setNombre(TextNombreConductor.getText());
        objConductor.setTelefono(TextTelefono.getText());
        return objConductor;
    }
    
    public void Limpiar (){
        TextIDConductor.setText("");
        TextNombreConductor.setText("");
        TextTelefono.setText("");
        
        AgregarBoton.setEnabled(true);
        EditarBoton.setEnabled(false);
        BorrarBoton.setEnabled(false);
    }
    
    public void MostrarDatos(){
        
        while (Modelo.getRowCount()>0){
            Modelo.removeRow(0);
        }
        Conexion obj1 = new Conexion ();
        try {
            ResultSet resultado = obj1.consultarRegistros("SELECT * FROM envios.conductor");
            while (resultado.next()) {
                System.out.println(resultado.getString("idConductor"));
                System.out.println(resultado.getString("Nombre"));
                System.out.println(resultado.getString("Telefono"));
                System.out.println("");
                
                Object []oUsuario = {resultado.getString("idConductor"), resultado.getString("Nombre"),resultado.getString("Telefono")};
                Modelo.addRow(oUsuario);
            }
        } catch (Exception e) {
            System.out.println("error: "+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConductor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton BorrarBoton;
    private javax.swing.JButton CancelarBoton;
    private javax.swing.JButton EditarBoton;
    private javax.swing.JTable TablaConductor;
    private javax.swing.JTextField TextIDConductor;
    private javax.swing.JTextField TextNombreConductor;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
